# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cv < Formula
  desc "CLI for the .cv open file format (PDF + Markdown + HTML + embeddings)"
  homepage "https://cvfile.org"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cvfile/cv/releases/download/v0.2.1/cv_0.2.1_macos_x86_64.tar.gz"
      sha256 "648fb03122ac00583c729b9a7885adcee86c412a23e3d0bcfad91596f1ca780d"

      define_method(:install) do
        bin.install "cv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cvfile/cv/releases/download/v0.2.1/cv_0.2.1_macos_arm64.tar.gz"
      sha256 "2454d18535fcea90910e5ed19d119e43a3a3641ac19e7b17df6522e3a11a72f9"

      define_method(:install) do
        bin.install "cv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cvfile/cv/releases/download/v0.2.1/cv_0.2.1_linux_x86_64.tar.gz"
      sha256 "272e08183ffe1dc3ed821e63a4fc930d4c0612876d6bf8fd408409e1f03eb474"
      define_method(:install) do
        bin.install "cv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cvfile/cv/releases/download/v0.2.1/cv_0.2.1_linux_arm64.tar.gz"
      sha256 "b1a62433b07a9244d95e7c71a3855cede4e67bd0e315dce742aa0df19449a84f"
      define_method(:install) do
        bin.install "cv"
      end
    end
  end

  test do
    assert_match "cv ", shell_output("#{bin}/cv version")
  end
end
